# Generated by Django 4.2.3 on 2023-07-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Officer',
            new_name='Team1',
        ),
    ]
