# Generated by Django 4.2.3 on 2023-07-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_rename_officer_team1'),
    ]

    operations = [
        migrations.AddField(
            model_name='team1',
            name='role',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
