# Generated by Django 4.2.3 on 2023-10-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_team1_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
